/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soccerleague;
import java.util.Comparator;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author Miguel Vargas
 */

public class FirstFrame extends javax.swing.JFrame {

    /**
     * Creates new form FirstFrame
     */
    public FirstFrame() {
        initComponents();      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        ManualGameBtn = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        autoGameBtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(255, 0, 0));

        ManualGameBtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        ManualGameBtn.setText("Manual Game");
        ManualGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManualGameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ManualGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(ManualGameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addGap(52, 52, 52))
        );

        jPanel3.setBackground(new java.awt.Color(51, 51, 255));

        autoGameBtn.setFont(new java.awt.Font("Tempus Sans ITC", 0, 12)); // NOI18N
        autoGameBtn.setText("Auto Game");
        autoGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoGameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(autoGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(176, 176, 176))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(autoGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 0));

        jLabel3.setFont(new java.awt.Font("Matura MT Script Capitals", 0, 12)); // NOI18N
        jLabel3.setText("COLOMBIAN SOCCER LEAGUE");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(73, 73, 73))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(62, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
//----------------------Buttom Events----------------------------------------
    
    
    private void autoGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoGameBtnActionPerformed
        //Buttom AutoGame Event
           
        SoccerTeam team1 = new SoccerTeam("Alianza FC");
        SoccerTeam team2 = new SoccerTeam("America de Cali");
        SoccerTeam team3 = new SoccerTeam("Atletico Bucaramanga");
        SoccerTeam team4 = new SoccerTeam("Chico");
        SoccerTeam team5 = new SoccerTeam("Deportivo Pereira");
        SoccerTeam team6 = new SoccerTeam("Envigado");
        SoccerTeam team7 = new SoccerTeam("Fortaleza");
        SoccerTeam team8 = new SoccerTeam("Jaguares FC");
        SoccerTeam team9 = new SoccerTeam("Junior");
        SoccerTeam team10 = new SoccerTeam("La Equidad");
        SoccerTeam team11 = new SoccerTeam("Medellin");
        SoccerTeam team12 = new SoccerTeam("Millonarios");
        SoccerTeam team13 = new SoccerTeam("Nacional");
        SoccerTeam team14 = new SoccerTeam("Once Caldas");
        SoccerTeam team15 = new SoccerTeam("Pasto");
        SoccerTeam team16 = new SoccerTeam("Patriotas");
        SoccerTeam team17 = new SoccerTeam("Rionegro");
        SoccerTeam team18 = new SoccerTeam("Santa Fe");
        SoccerTeam team19 = new SoccerTeam("Tolima");
        SoccerTeam team20 = new SoccerTeam("Deportivo Cali");
        
            //List with every team
        SoccerTeam list1 [] = {team1,team2,team3,team4,team5,team6,team7,team8,team9,team10,team11,team12,team13,team14,team15,team16,team17,team18,team19,team20};
         SoccerTeam list2 [] = {team1,team2,team3,team4,team5,team6,team7,team8,team9,team10,team11,team12,team13,team14,team15,team16,team17,team18,team19,team20};
        
        for (int i =0; i<20;i++){
        for (int j=0;j<20;j++){          
            if(list1[i].getPlayedTeams().contains(list2[j])==false && list1[i]!=list2[j]){  //one team cannot play with other team again               
                SoccerTeam.playMatch(list1[i],list2[j]);                            
            }                  
          }     
        }
        
      //  Sorting list1 for the positions depending the points
        Comparator<SoccerTeam> comparador = (p1, p2) -> Integer.compare(p2.getPoints(), p1.getPoints());     
        Arrays.sort(list1, comparador);
          
         System.out.println("Los Puestos son los siguientes, listos para mostrar al usuario");
        for(SoccerTeam variable : list1){
            System.out.println(variable.getName());
        }
        
       TableFrame form2 = new TableFrame(); 
        form2.setDato(list1);
        form2.setVisible(true);                 //Open the other jframe
        form2.setForm(form2);
        
         frame1.dispose();
    //End AUTO BUTTOM EVENT
    }//GEN-LAST:event_autoGameBtnActionPerformed

    private void ManualGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManualGameBtnActionPerformed
        //Manual Game buttom event
          SoccerTeam team1 = new SoccerTeam("Alianza FC");
        SoccerTeam team2 = new SoccerTeam("America de Cali");
        SoccerTeam team3 = new SoccerTeam("Atletico Bucaramanga");
        SoccerTeam team4 = new SoccerTeam("Chico");
        SoccerTeam team5 = new SoccerTeam("Deportivo Pereira");
        SoccerTeam team6 = new SoccerTeam("Envigado");
        SoccerTeam team7 = new SoccerTeam("Fortaleza");
        SoccerTeam team8 = new SoccerTeam("Jaguares FC");
        SoccerTeam team9 = new SoccerTeam("Junior");
        SoccerTeam team10 = new SoccerTeam("La Equidad");
        SoccerTeam team11 = new SoccerTeam("Medellin");
        SoccerTeam team12 = new SoccerTeam("Millonarios");
        SoccerTeam team13 = new SoccerTeam("Nacional");
        SoccerTeam team14 = new SoccerTeam("Once Caldas");
        SoccerTeam team15 = new SoccerTeam("Pasto");
        SoccerTeam team16 = new SoccerTeam("Patriotas");
        SoccerTeam team17 = new SoccerTeam("Rionegro");
        SoccerTeam team18 = new SoccerTeam("Santa Fe");
        SoccerTeam team19 = new SoccerTeam("Tolima");
        SoccerTeam team20 = new SoccerTeam("Deportivo Cali");
        
            //List with every team
        SoccerTeam list1 [] = {team1,team2,team3,team4,team5,team6,team7,team8,team9,team10,team11,team12,team13,team14,team15,team16,team17,team18,team19,team20};
         SoccerTeam list2 [] = {team1,team2,team3,team4,team5,team6,team7,team8,team9,team10,team11,team12,team13,team14,team15,team16,team17,team18,team19,team20};
  
        ManualFrame frameM = new ManualFrame();
        
        frameM.setDato(list1, list2);  //Transpost the two lists
    
        frameM.setVisible(true);
        frameM.setForm(frameM);
        frame1.dispose();

        //END manual buttom event
    }//GEN-LAST:event_ManualGameBtnActionPerformed

      
      static FirstFrame frame1 = new FirstFrame();       //My own instance of the frame 1
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FirstFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                 frame1.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManualGameBtn;
    private javax.swing.JButton autoGameBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables







}



