/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soccerleague;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Vargas
 */
public class TableFrame extends javax.swing.JFrame {
    
      
    
    
     private SoccerTeam [] list1;
    public void setDato(SoccerTeam [] list){
    this.list1=list;
    }
    
    
    
   
  
   
    
    
     //Creates new form TableFrame    
    public TableFrame() {       //Main
        initComponents();
       
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pruebaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        positionTable = new javax.swing.JTable();
        winnerlbl = new javax.swing.JLabel();
        winnerrlbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pruebaBtn.setText("See Resutls");
        pruebaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pruebaBtnActionPerformed(evt);
            }
        });

        positionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Posiciones", "Equipo", "Partidos Jugados", "Partidos Ganados", "Partidos perdidos", "Goles en Anotados", "Goles en Contra"
            }
        ));
        jScrollPane1.setViewportView(positionTable);

        winnerlbl.setText("..");

        winnerrlbl.setText("...");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(winnerrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pruebaBtn)))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(winnerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(winnerlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(pruebaBtn)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(winnerrlbl)
                        .addGap(25, 25, 25))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
  
    
    
    
    
   
    private void pruebaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pruebaBtnActionPerformed
         DefaultTableModel table = new DefaultTableModel();
         
         /*
        for (int i =0; i<8;i++){
            System.out.println("-----------------------");
            System.out.println(list1[i].getName());      
        }
        */     
         
         table.addColumn("Índice");
    table.addColumn("Nombre");
    table.addColumn("Partidos Jugados");
    table.addColumn("Partidos Ganados");
    table.addColumn("Partidos Perdidos");
    table.addColumn("Goles a favor");
    table.addColumn("Goles en contra");
    table.addColumn("Points");
    
    
        int position =1;
        int anterior=0;
         for  (int i = 0;i<19;i++){
                     table.addRow(new Object[]{
            position,
            list1[i].getName(),
            list1[i].getMatchsPlayed(),
            list1[i].getWinMatch(),
            list1[i].getLoseMatch(),
            list1[i].getGoalsWin(),
            list1[i].getGoalsLose(),
            list1[i].getPoints()                                            
                     });
             if(list1[i].getPoints()!=list1[i+1].getPoints())  {
             position++;        
             }                                           
                }    
              positionTable.setModel(table);
              
              String winner = list1[0].getName();
              
              
         winnerlbl.setText("The winner of the Colombian soccer league is                                 !!" );
         winnerrlbl.setText(winner);
    }//GEN-LAST:event_pruebaBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TableFrame().setVisible(true);
            }
        });
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable positionTable;
    private javax.swing.JButton pruebaBtn;
    private javax.swing.JLabel winnerlbl;
    private javax.swing.JLabel winnerrlbl;
    // End of variables declaration//GEN-END:variables
}
