/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package soccerleague;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miguel Vargas
 */
public class TableFrame extends javax.swing.JFrame {
    
      
    
    
     private SoccerTeam [] list1;   //Methon for transport de dates of a frame to other
    public void setDato(SoccerTeam [] list){
    this.list1=list;
    }
    
    TableFrame frame1;
    
     public void setForm(TableFrame form){      //Funtion for send the instance to the other form
    this.frame1=form;
    }
   
  
   
    
    
     //Creates new form TableFrame    
    public TableFrame() {       //Main
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pruebaBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        positionTable = new javax.swing.JTable();
        winnerlbl = new javax.swing.JLabel();
        winnerrlbl = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pruebaBtn.setText("See Resutls");
        pruebaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pruebaBtnActionPerformed(evt);
            }
        });

        positionTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Positions", "Teams", "Games Played", "Games won", "Games Lost", "Goals in favor", "Goles Against"
            }
        ));
        jScrollPane1.setViewportView(positionTable);

        winnerlbl.setText("..");

        winnerrlbl.setText("...");

        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 572, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(backBtn)
                        .addGap(141, 141, 141)
                        .addComponent(winnerrlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pruebaBtn))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(128, 128, 128)
                        .addComponent(winnerlbl, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(winnerlbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(winnerrlbl)
                            .addComponent(pruebaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(backBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

 
  
    
    
    
    
   
    private void pruebaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pruebaBtnActionPerformed
         DefaultTableModel table = new DefaultTableModel();
             
    table.addColumn("Position");          //Add de columns names to the model
    table.addColumn("Team");
    table.addColumn("games played");
    table.addColumn("matches won");
    table.addColumn("lost matches");
    table.addColumn("Goals in favor");
    table.addColumn("goals against");
    table.addColumn("Points");
    
    
        int position =1;
     //   int anterior=0;
         for  (int i = 0;i<19;i++){     //Add for each row the respectives dates to the model
                     table.addRow(new Object[]{
            position,
            list1[i].getName(), 
            list1[i].getMatchsPlayed(),
            list1[i].getWinMatch(),
            list1[i].getLoseMatch(),
            list1[i].getGoalsWin(),
            list1[i].getGoalsLose(),
            list1[i].getPoints()                                            
                     });
             if(list1[i].getPoints()!=list1[i+1].getPoints())  {
             position++;        
             }                                           
                }    
              positionTable.setModel(table);    //Vinculate the model with the table
      
              
              String winner = list1[0].getName();                   //Winner message
         winnerlbl.setText("The winner of the Colombian soccer league is                                 !!" );
         winnerrlbl.setText(winner);
         
         //End seeResultButtom event
    }//GEN-LAST:event_pruebaBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        FirstFrame frameAux = new FirstFrame();       
        frameAux.setVisible(true);
       frame1.dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
     static TableFrame frame12 = new TableFrame(); 
    public static void main(String args[]) {      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                frame12.setVisible(true);
            }
        });
        
        
        
        
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable positionTable;
    private javax.swing.JButton pruebaBtn;
    private javax.swing.JLabel winnerlbl;
    private javax.swing.JLabel winnerrlbl;
    // End of variables declaration//GEN-END:variables
}
